---
apiVersion: v1
kind: Template
metadata:
  name: postgres-dba
parameters:
- name: DB_SECRET
  value: ""
- name: PGCONNECT_TIMEOUT
  value: "30"
- name: PGSSLMODE
  value: "require"
- name: DB_INIT_CONTAINER
  value: ""
- name: DB_INIT_CONTAINER_TAG
  value: ""
- name: DB_INIT_SCRIPTS_CONFIGMAP
  value: ""
objects:
